### ISSUE TITLE
Error in excution in DrQA file

### ISSUE THREAD

**Issue by basharathussain** [kushalj001/pytorch-question-answering#1]
Hi,

I need a clarification regarding an error found in DrQA file. 

Its in the function create_word_embedding the variable vocab not found. 
Will you please suggest a correction 

Thanks in advance 
![Untitled](https://user-images.githubusercontent.com/8046505/91425667-df64d880-e874-11ea-92bc-9a2b00aad569.png)

**Comment by kushalj001** [comment]
That should be `word_vocab` that you get as an output from `build_word_vocab` above. I'll update it. 
Thanks for pointing this out.

**Comment by basharathussain** [comment]
Thank you for your reply. 
then after changing to word_vocab - and after executing, I am wondering I get following results with EM = 0

![image](https://user-images.githubusercontent.com/8046505/91521958-69af4a00-e912-11ea-9374-22a95c8846e3.png)

Please suggest or  if you need more information from me, please write. I haven't changes the code but downloaded three files and used: 1. glove.840B.300d.txt (5GB), 2. dataset-Squad/train-v1.0.json (28MB)  3. dataset-Squad/dev-v1.0.json (4MB).
 
I am very much passionate understanding first model DrQA in NLP.  thanks in advance.

**Comment by basharathussain** [comment]
Hi, 
Please write your personal email address, I like to extend this work. 
Thank you and stay happy,
Basharat

**Comment by kushalj001** [comment]
> Please suggest or if you need more information from me, please write. I haven't changed the code but downloaded three files and used: 1. glove.840B.300d.txt (5GB), 2. dataset-Squad/train-v1.0.json (28MB) 3. dataset-Squad/dev-v1.0.json (4MB).

The notebooks have been tested for SQUAD v1.1. I'll push the JSON files for convenience. I tested the DrQA notebook again and I am getting good results.

**Comment by basharathussain** [comment]
Thank you very much for your  prompt support - I am able to get the expected results for DrQA model.

**Comment by kushalj001** [comment]
Closing this now. Feel free to open it again if needed.
