### ISSUE TITLE
QANet executed with an error

### ISSUE THREAD

**Issue by basharathussain** [kushalj001/pytorch-question-answering#2]
Hi, 

I tried to execute QANet. 
It raiseed with an error:
![image](https://user-images.githubusercontent.com/8046505/91603358-48884100-e986-11ea-9602-38d83da9f27d.png)

Reason looks somthing index is out of range. 
idx2word cotains lesser elements while code tries to access idx2word[105844]
Something in tensor needs attention. 

Your help is appreciated. Thanks again.

**Comment by kushalj001** [comment]
This issue was occurring due to wrong file names while loading pickle files for `word2idx` and `char2idx`. It was initially loading the pickle files saved from the BIDAF notebook. It has been fixed now. Thank you for bringing this to my notice.
